"""empty message

Revision ID: 295815cf2339
Revises: 11e48b1d9779
Create Date: 2025-03-01 02:02:26.276289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295815cf2339'
down_revision = '11e48b1d9779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_home_planet_id_fkey', type_='foreignkey')
        batch_op.drop_column('home_planet_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_planet_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('people_home_planet_id_fkey', 'planet', ['home_planet_id'], ['id'])

    # ### end Alembic commands ###
